# Generated by Django 3.1.2 on 2020-10-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCRTestsSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(blank=True)),
                ('cough', models.BooleanField()),
                ('fever', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('shortness_of_breath', models.BooleanField()),
                ('head_ache', models.BooleanField()),
                ('corona_result', models.BooleanField()),
                ('age_60_and_above', models.BooleanField()),
                ('gender', models.CharField(max_length=200)),
                ('test_indication', models.CharField(max_length=200)),
            ],
        ),
    ]
