# Generated by Django 3.1.2 on 2020-10-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='age_60_and_above',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='corona_result',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='cough',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='fever',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='head_ache',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='shortness_of_breath',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='sore_throat',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pcrtestssymptoms',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
