# Generated by Django 3.1.2 on 2020-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_auto_20201005_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('corona_result', models.BooleanField(null=True)),
                ('lab_id', models.IntegerField(null=True)),
                ('test_for_corona_diagnosis', models.BooleanField(null=True)),
                ('is_first_Test', models.BooleanField(null=True)),
            ],
        ),
    ]
