# Generated by Django 3.1.2 on 2020-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0003_alltests'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid19apidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Deaths', models.IntegerField(null=True)),
                ('Recovered', models.IntegerField(null=True)),
                ('Active', models.IntegerField(null=True)),
                ('daily_Deaths', models.IntegerField(null=True)),
                ('daily_Recovered', models.IntegerField(null=True)),
                ('daily_Active', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deaths_no_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200, null=True)),
                ('age_group', models.CharField(max_length=200, null=True)),
                ('Ventilated', models.BooleanField(null=True)),
                ('Time_between_positive_and_hospitalization', models.FloatField(null=True)),
                ('Length_of_hospitalization', models.FloatField(null=True)),
                ('Time_between_positive_and_death', models.FloatField(null=True)),
            ],
        ),
    ]
