# Generated by Django 3.1.2 on 2020-10-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0005_auto_20201012_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_PCRTestsSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(blank=True, null=True)),
                ('alltests', models.IntegerField(null=True)),
                ('withsymptoms', models.IntegerField(null=True)),
                ('allpos', models.IntegerField(null=True)),
                ('poswithwithsymptoms', models.IntegerField(null=True)),
            ],
        ),
    ]
