# Generated by Django 3.1.2 on 2020-10-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0007_agg_alltests'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total_hospitalised', models.IntegerField(null=True)),
                ('perc_hospitalised_female', models.FloatField(null=True)),
                ('avg_age', models.FloatField(null=True)),
                ('std_div_age', models.FloatField(null=True)),
                ('ventilated', models.IntegerField(null=True)),
                ('perc_female_ventilated', models.FloatField(null=True)),
                ('avg_age_ventilated', models.FloatField(null=True)),
                ('std_div_age_ventilated', models.FloatField(null=True)),
                ('mild', models.IntegerField(null=True)),
                ('perc_mild_female', models.FloatField(null=True)),
                ('avg_age_mild', models.FloatField(null=True)),
                ('std_div_age_mild', models.FloatField(null=True)),
                ('modarate', models.IntegerField(null=True)),
                ('perc_modarate_female', models.FloatField(null=True)),
                ('avg_age_modarate', models.FloatField(null=True)),
                ('std_div_age_modarate', models.FloatField(null=True)),
                ('severe', models.IntegerField(null=True)),
                ('perc_severe_female', models.FloatField(null=True)),
                ('avg_age_severe', models.FloatField(null=True)),
                ('std_div_age_severe', models.FloatField(null=True)),
                ('severe_cumulative', models.IntegerField(null=True)),
            ],
        ),
    ]
